### ISSUE TITLE
Round the axis limits

### ISSUE THREAD

**Issue by waldyrious** [sunetos/TextPlots.jl#5]
In the x axis, if I pass, say, `6pi` I'd like to see that in the graph, not 18.8495 as seen [here](https://github.com/JuliaLang/openlibm/issues/57#issuecomment-44225633).

In the y axis, there should probably be some threshold for rounding (say, 1/100th of the covered range), so instead of -0.99899 to 0.99899 (see the example linked above), TextPlots would use -1 to 1. Even better if it applies the threshold to approximate known constants like _e_, sqrt(2), [simple fractions](https://en.wikipedia.org/wiki/Diophantine_approximation), etc. -- but that's probably wishful thinking for now :)

**Comment by waldyrious** [comment]
Ah, I just remembered where I had read about the [conversion of decimal numbers to fractions](http://rosettacode.org/wiki/Convert_decimal_number_to_rational#Julia). Seems like it wouldn't be hard to implement, by passing an adaptive tolerance parameter.

**Comment by sunetos** [comment]
I think doing this would require converting to a macro, because all I get in the plot function is a floating-point number (I can't know that you originally typed 6pi). With a macro I could parse the arguments symbolically. This would add a decent bit of complexity to the code. It does already try to round intelligently based on the available digits with the specified margin width.

**Comment by waldyrious** [comment]
Fair enough. But even without knowing what the user typed, I suppose the rounding could be improved, particularly for the y axis. One suggestion is to use a reasonable threshold as I suggested above (1/100th of the covered range or something to that effect), but I'm sure other heuristics can be devised.

If something like that is implemented, I'd then suggest deprecating the `margin` option, which, apart from the rounding, doesn't seem otherwise as relevant/necessary as the other sizing options.

**Comment by sunetos** [comment]
Good point on the relative scale; I'll look into that. The margin option is 
staying, because it's necessary to allow users to make multiple plots that 
all fit in the same exact output dimensions.

**Comment by waldyrious** [comment]
I see. In that case, it perhaps wouldn't hurt making that suggestion in the README examples involving the margin option. Currently, the only mention of an use/effect of the margin option is the rounding, which may be misleading, especially if another rounding method is implemented.

**Comment by sunetos** [comment]
I've added a decent number of attempts at smarter formatting of the axis limits. As for the documentation on the options, I will expand that when it's clear there are more users of this library.
